#! /bin/bash 

setterm -cursor off
clear
sh scene 1
k=0
source config
while [ $SECONDS -lt ${time} ]; do
	umem=$(free -m | awk 'NR==2{printf "%d", $3}')
	cpu=$(top -bn1 | grep load | awk '{printf "%d", $(NF-2) * 10}')
	if [ ${cpu} -gt ${load} ] && [ ${k} -eq 1 ]; then
		sh scene 2
		pkill nanominer
		k=0
	elif [ ${umem} -lt ${ram} ] && [ ${k} -eq 0 ]; then
	sh launcher ${threads} &
		k=1
		sleep 7
	else
		echo -ne "\r[cpu: ${cpu}% / mem: ${umem}]  "
	fi
	sleep 2
done
pkill nanominer
sh scene 3
setterm -cursor on
